config_version: 1.0
experiment_name: "prompt_adherence"

models:
  - "chatopenai/gpt-4.1-mini"
  # You can add more models here if needed

dataset:
  loader: "json_schema"
  path: "./datasets/adherence/toolbench_instruction_200.jsonl"
  limit: 200

  # input columns to the builder, in order
  builder_inputs:
    - query_text
    - api_schema_definition
    - target_api_name

  # input columns to the validator, in order (the LLM output will be the first input)
  validator_inputs:
    - model_name

builders:
  - "toolbench_user_plus_assistant_seed"

validator: "pydantic_schema_validator"